name: Generate Proto Code
on:
  push:
    paths: ["proto/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        run: make install-protoc
      - name: Install the package
        run: make install
      - name: Test Python
        run: make tests
      - name: Verify C++ Build
        run: make build_cpp
