name: Generate Proto Code
on:
  push:
    paths: ["proto/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Install uv and set up the Python environment
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Automatically use the version in .python-version or pyproject.toml
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Protoc
        run: make install-protoc
      - name: Install the package
        run: make install
      - name: Test Python
        run: make tests
      - name: Verify C++ Build
        run: make build_cpp
